### PR TITLE
Restaurant Page

### PR DESCRIPTION
**Pull request by haraphat01**
This is my final submission on the Restaurant Solo Page, the site is built with Html, CSS, and Javascript. All the documents on the site are added through the DOM.

The site has three tabs, which are;

- Home 

- Menu

- Contact

Kindly Review for your kind approval

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @haraphat01 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] We recommend you use es6 function, see below
```
export default const container = () => {
 # Your code
}
```
- [ ] In the scripts in package.json, add more scripts and make it much better to standards
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
- [ ] Make the text in the web pages visible and readable
### Make these changes and submit for another code review. Good luck!
- Happy coding!

**Comment by haraphat01** [comment]
It was ES6 I used initially, but the ES linters wasn't accepting it, as it was throwing an error, I had to change it. 

I just changed it to what you what, but it's still showing lint errors.
linter

**Review by rOluochKe — COMMENTED** [review]
Hello @haraphat01 
### Once again good job, fix the errors:-
- [ ] Declare the function and export after
### Submit for another code review after making the changes. Good luck.
- Happy coding!

**Comment by Dandush03** [comment]
# Status: :rocket: Approved :rocket: 
### Great Work Implementing Changes :muscle: 
# Happy Coding :tophat:

**Pull request merged**
